server:
  port: 8089
spring:  application:    name: CHECK-SERVICE
eureka:  client:    service-url:      default-zone: http://localhost:8761/
    
#ORDER-SERVICE:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:7081,localhost:7083,localhost:7082        
  