server:
  port: 8081
spring:  application:    name: BOOK-SERVICE
#  data:#    mongodb:#      uri:  mongodb://localhost/test 
eureka:  client:    service-url:      default-zone: http://localhost:8761/
    
  